name: .NET Core

on:
  push:
    paths:
    - 'api/**.cs'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build with dotnet
      working-directory: ./api
      run: dotnet build --configuration Release
